sudo: required
dist: trusty
language: rust
rust:
- stable
- beta
- nightly
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    - gcc-5
    - g++-5
    - clang-3.6
